
-- AlterTable
ALTER TABLE "Station" ADD COLUMN     "borough" TEXT NOT NULL DEFAULT 'Unknown',
ADD COLUMN     "latitude" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "longitude" DOUBLE PRECISION NOT NULL DEFAULT 0.0;
